[Rutas]
# Carpeta donde se encuentran las 10 carpetas de palabras
carpeta_grabaciones = grabaciones_segmentadas
# Nombre del archivo donde se guardará el análisis
archivo_csv = resultados_analisis_ajustado.csv

[Parametros]
# --- Pitch (F0) ---
# Piso: 75 para hombres, 100 para mujeres
pitch_floor = 100.0
# Techo: 300 para hombres, 500-600 para mujeres (300 ayuda a evitar armónicos en 8kHz)
pitch_ceiling = 500.0

# --- Formantes ---
# Frecuencia máxima: 4000.0 es el límite real para audio de 8000Hz (Nyquist)
max_formante = 4000.0

# --- LPC ---
# Orden sugerido: (Frecuencia_muestreo / 1000) + 2 = 8 + 2 = 10
lpc_valor = 10

# --- MFCC ---
# 13 coeficientes es el estándar en reconocimiento de voz y bioseñales
mfcc_valor = 13