[Rutas]
# Carpeta donde se encuentran las 10 carpetas de palabras
carpeta_grabaciones = grabaciones_segmentadas
# Nombre del archivo donde se guardará el análisis
# diferenciarlo del análisis ajustado
archivo_csv = resultados_analisis_default.csv

[Parametros]
# --- Pitch (F0) ---
# El valor estándar de Praat para el rango de búsqueda
pitch_floor = 75.0
pitch_ceiling = 500.0

# --- Formantes ---
# Praat usa 5500.0 Hz por defecto (basado en un tracto vocal femenino estándar)
max_formante = 5500.0

# --- LPC ---
# El orden de predicción por defecto en los algoritmos de Praat suele ser 16
lpc_valor = 16

# --- MFCC ---
# El valor estándar por defecto para coeficientes MFCC es 12
mfcc_valor = 12